import type { MeetingExportData, ActionItem } from './types';

export function exportMarkdown(data: MeetingExportData): string {
  const bullets = (arr?: string[]) =>
    arr && arr.length ? arr.map((v) => `- ${v}`).join('\n') : '_(none)_';

  const table = (rows: ActionItem[]) => [
    '| Owner | Task | Due | Priority |',
    '|-------|------|-----|-----------|',
    ...(rows.length
      ? rows.map(
          (a) =>
            `| ${a.owner || 'Unassigned'} | ${a.task || ''} | ${a.due || 'N/A'} | ${
              a.priority || 'N/A'
            } |`
        )
      : ['| _ | _ | _ | _ |']),
  ].join('\n');

  const transcript = (data.transcript || [])
    .map((t) => `**[${t.start}] ${t.speaker || 'Speaker'}:** ${t.text || ''}`)
    .join('\n');

  return [
    '# 🧠 JARVIX Meeting Summary',
    '',
    `**Meeting Title:** ${data.title}`,
    `**Date:** ${data.date}`,
    `**Participants:** ${(data.participants || []).join(', ')}`,
    '',
    '---',
    '## 🧾 Executive Summary',
    bullets(data.summary),
    '',
    '## ✅ Key Decisions',
    bullets(data.decisions),
    '',
    '## 📋 Action Items',
    table(data.actionItems || []),
    '',
    '## 🗒️ Full Transcript',
    transcript,
    '',
    '---',
    '*Generated by JARVIX Assistant — Real‑Time Meeting Intelligence.*',
  ].join('\n');
}

export const exportText = (d: MeetingExportData): string =>
  [
    `Meeting Title: ${d.title}`,
    `Date: ${d.date}`,
    `Participants: ${(d.participants || []).join(', ')}`,
    '',
    'Summary:',
    ...(d.summary || []),
    '',
    'Decisions:',
    ...(d.decisions || []),
    '',
    'Action Items:',
    ...(d.actionItems || []).map(
      (a) =>
        `${a.owner || 'Unassigned'} - ${a.task || ''} (${a.due || 'N/A'}, ${a.priority || 'N/A'})`
    ),
    '',
    'Transcript:',
    ...(d.transcript || []).map((t) => `[${t.start}] ${t.speaker || 'Speaker'}: ${t.text || ''}`),
  ].join('\n');

export const exportJSON = (d: MeetingExportData): string => JSON.stringify(d, null, 2);

